/**
 * @module shared/contracts/admin/tag
 *
 * Tag Master admin contracts (Wave 3 Phase A · W3-3).
 *
 * Source-of-truth alignment:
 *  - Spec: requirements.md §15.3 + feature-voc.md §9.4.6 (D22, OQ-1 Option D, ADR 0004).
 *  - DB: backend/migrations/004_tags.sql + 014_tag_master_ops.sql (W3-1).
 *  - OpenAPI: shared/openapi.yaml — TagMasterItem / TagMasterCreate / TagMasterPatch /
 *    TagMasterMergeInput / TagRuleSuspendInput.
 *
 * Permission matrix (enforced BE-side):
 *   - Read (list)          : Admin / Manager / Dev
 *   - Manager+ mutate      : POST /api/admin/tags        (TagMasterCreate)
 *                            PATCH /api/admin/tags/:id   (TagMasterPatch — name only)
 *   - Admin only mutate    : POST   /api/admin/tags/:id/merge   (TagMasterMergeInput)
 *                            PATCH  /api/admin/tags/:id/external (TagExternalToggle)
 *                            DELETE /api/admin/tags/:id          (사용 VOC=0 + 규칙 참조 0)
 *                            PATCH  /api/admin/tag-rules/:id/suspend (TagRuleSuspendInput)
 */
import { z } from 'zod';
import { Uuid } from '../common';

const Iso = z.string().datetime({ offset: true });

export const TagKind = z.enum(['general', 'menu']);
export type TagKind = z.infer<typeof TagKind>;

/**
 * Row shape for Tag Master list (`GET /api/admin/tags`).
 * Includes operational columns from migration 014 + computed `usage_count`.
 */
export const TagMasterItem = z.object({
  id: Uuid,
  name: z.string().min(1),
  slug: z.string().min(1),
  kind: TagKind,
  is_external: z.boolean(),
  merged_into_id: Uuid.nullable(),
  usage_count: z.number().int().nonnegative(),
  rule_ref_count: z.number().int().nonnegative(),
  created_at: Iso,
});
export type TagMasterItem = z.infer<typeof TagMasterItem>;

export const TagMasterListQuery = z.object({
  kind: TagKind.optional(),
  q: z.string().trim().max(120).optional(),
  page: z.coerce.number().int().positive().default(1),
  per_page: z.coerce.number().int().min(1).max(100).default(20),
});
export type TagMasterListQuery = z.infer<typeof TagMasterListQuery>;

export const TagMasterListResponse = z.object({
  rows: z.array(TagMasterItem),
  page: z.number().int().positive(),
  per_page: z.number().int().positive(),
  total: z.number().int().nonnegative(),
});
export type TagMasterListResponse = z.infer<typeof TagMasterListResponse>;

/** POST /api/admin/tags — Manager+. Slug auto-generated by BE. */
export const TagMasterCreate = z.object({
  name: z.string().trim().min(1).max(80),
  kind: TagKind,
});
export type TagMasterCreate = z.infer<typeof TagMasterCreate>;

/** PATCH /api/admin/tags/:id — Manager+. Only `name` mutable (kind locked, slug legacy-protected). */
export const TagMasterPatch = z.object({
  name: z.string().trim().min(1).max(80),
});
export type TagMasterPatch = z.infer<typeof TagMasterPatch>;

/** POST /api/admin/tags/:id/merge — Admin only. Re-points voc_tags + tag_rules to target then deletes source. */
export const TagMasterMergeInput = z.object({
  targetId: Uuid,
});
export type TagMasterMergeInput = z.infer<typeof TagMasterMergeInput>;

/** PATCH /api/admin/tags/:id/external — Admin only. Toggle `tags.is_external`. */
export const TagExternalToggle = z.object({
  is_external: z.boolean(),
});
export type TagExternalToggle = z.infer<typeof TagExternalToggle>;

/** PATCH /api/admin/tag-rules/:id/suspend — Admin only. NULL = resume immediately. */
export const TagRuleSuspendInput = z.object({
  suspended_until: Iso.nullable(),
});
export type TagRuleSuspendInput = z.infer<typeof TagRuleSuspendInput>;

export const TagIdParam = z.object({ id: Uuid });
export type TagIdParam = z.infer<typeof TagIdParam>;
