/**
 * @module shared/contracts/admin/tag
 *
 * Tag Master admin contracts (Wave 3 Phase A · W3-3).
 *
 * Source-of-truth alignment:
 *  - Spec: requirements.md §15.3 + feature-voc.md §9.4.6 (D22, OQ-1 Option D, ADR 0004).
 *  - DB: backend/migrations/004_tags.sql + 014_tag_master_ops.sql (W3-1).
 *  - OpenAPI: shared/openapi.yaml — TagMasterItem / TagMasterCreate / TagMasterPatch /
 *    TagMasterMergeInput / TagRuleSuspendInput.
 *
 * Permission matrix (enforced BE-side):
 *   - Read (list)          : Admin / Manager / Dev
 *   - Manager+ mutate      : POST /api/admin/tags        (TagMasterCreate)
 *                            PATCH /api/admin/tags/:id   (TagMasterPatch — name only)
 *   - Admin only mutate    : POST   /api/admin/tags/:id/merge   (TagMasterMergeInput)
 *                            PATCH  /api/admin/tags/:id/external (TagExternalToggle)
 *                            DELETE /api/admin/tags/:id          (사용 VOC=0 + 규칙 참조 0)
 *                            PATCH  /api/admin/tags/:tagId/rules/:ruleId/suspend (TagRuleSuspendInput)
 *
 * Tag Rules (Phase 01 — D-08 nested resource):
 *   GET    /api/admin/tags/:tagId/rules                (TagRuleListQuery → TagRuleListResponse)
 *   POST   /api/admin/tags/:tagId/rules                (TagRuleCreate → TagRule)
 *   PATCH  /api/admin/tags/:tagId/rules/:ruleId        (TagRulePatch → TagRule)
 *   DELETE /api/admin/tags/:tagId/rules/:ruleId
 *   PATCH  /api/admin/tags/:tagId/rules/:ruleId/suspend (TagRuleSuspendInput → TagRule)
 */
import { z } from 'zod';
import { Uuid } from '../common';

const Iso = z.string().datetime({ offset: true });

export const TagKind = z.enum(['general', 'menu']);
export type TagKind = z.infer<typeof TagKind>;

/**
 * Row shape for Tag Master list (`GET /api/admin/tags`).
 * Includes operational columns from migration 014 + computed `usage_count`.
 *
 * NOTE: `merged_into_id` removed per Resolution α (PR #251) — merge action is
 * hard-delete (source row removed, voc_tags rewired to target). Audit trail
 * deferred (no tombstone column). See feature-voc.md §9.4.6.
 */
export const TagMasterItem = z.object({
  id: Uuid,
  name: z.string().min(1),
  slug: z.string().min(1),
  kind: TagKind,
  is_external: z.boolean(),
  usage_count: z.number().int().nonnegative(),
  rule_ref_count: z.number().int().nonnegative(),
  created_at: Iso,
});
export type TagMasterItem = z.infer<typeof TagMasterItem>;

export const TagMasterListQuery = z.object({
  kind: TagKind.optional(),
  q: z.string().trim().max(120).optional(),
  page: z.coerce.number().int().positive().default(1),
  per_page: z.coerce.number().int().min(1).max(100).default(20),
});
export type TagMasterListQuery = z.infer<typeof TagMasterListQuery>;

export const TagMasterListResponse = z.object({
  rows: z.array(TagMasterItem),
  page: z.number().int().positive(),
  per_page: z.number().int().positive(),
  total: z.number().int().nonnegative(),
});
export type TagMasterListResponse = z.infer<typeof TagMasterListResponse>;

/** POST /api/admin/tags — Manager+. Slug auto-generated by BE. */
export const TagMasterCreate = z.object({
  name: z.string().trim().min(1).max(80),
  kind: TagKind,
});
export type TagMasterCreate = z.infer<typeof TagMasterCreate>;

/** PATCH /api/admin/tags/:id — Manager+. Only `name` mutable (kind locked, slug legacy-protected). */
export const TagMasterPatch = z.object({
  name: z.string().trim().min(1).max(80),
});
export type TagMasterPatch = z.infer<typeof TagMasterPatch>;

/** POST /api/admin/tags/:id/merge — Admin only. Re-points voc_tags + tag_rules to target then deletes source. */
export const TagMasterMergeInput = z.object({
  targetId: Uuid,
});
export type TagMasterMergeInput = z.infer<typeof TagMasterMergeInput>;

/** PATCH /api/admin/tags/:id/external — Admin only. Toggle `tags.is_external`. */
export const TagExternalToggle = z.object({
  is_external: z.boolean(),
});
export type TagExternalToggle = z.infer<typeof TagExternalToggle>;

/** PATCH /api/admin/tags/:tagId/rules/:ruleId/suspend — Admin only. NULL = resume immediately. */
export const TagRuleSuspendInput = z.object({
  suspended_until: Iso.nullable(),
});
export type TagRuleSuspendInput = z.infer<typeof TagRuleSuspendInput>;

export const TagIdParam = z.object({ id: Uuid });
export type TagIdParam = z.infer<typeof TagIdParam>;

/* -------------------------------------------------------------------------
 * Tag Rules — Phase 01 consolidation
 *  - D-05/D-06: pattern → keywords[] + match_mode (single 'keyword' enum, OQ-R1 Option C).
 *  - D-07:    TagRuleCreate / TagRulePatch OMIT created_by (server reads req.user.id).
 *  - D-08:    nested under /admin/tags/:tagId/rules (resource ownership reflects FK).
 *  - D-12 + OQ-R5: created_by uuid|null + created_by_name string|null (BE join).
 *  - kind:    locked to 'general' for v1 (menu rules deferred).
 * ------------------------------------------------------------------------- */

// T-01-11: cap keyword input size — at most 50 keywords per rule, each ≤60 chars.
const KeywordItem = z.string().trim().min(1).max(60);
const KeywordsArray = z.array(KeywordItem).min(1).max(50);

export const TagRule = z.object({
  id: Uuid,
  tag_id: Uuid,
  kind: z.literal('general'),
  keywords: KeywordsArray,
  match_mode: z.enum(['keyword']),
  suspended_until: Iso.nullable(),
  created_by: Uuid.nullable(),
  created_by_name: z.string().nullable(),
  created_at: Iso,
});
export type TagRuleT = z.infer<typeof TagRule>;

/** POST /api/admin/tags/:tagId/rules — Manager+. Server derives created_by from req.user.id. */
export const TagRuleCreate = z.object({
  keywords: KeywordsArray,
  match_mode: z.enum(['keyword']).default('keyword'),
});
export type TagRuleCreateT = z.infer<typeof TagRuleCreate>;

/** PATCH /api/admin/tags/:tagId/rules/:ruleId — Manager+. Body fields all optional; created_by immutable. */
export const TagRulePatch = z.object({
  keywords: KeywordsArray.optional(),
  match_mode: z.enum(['keyword']).optional(),
});
export type TagRulePatchT = z.infer<typeof TagRulePatch>;

export const TagRuleListQuery = z.object({
  q: z.string().trim().max(120).optional(),
  page: z.coerce.number().int().min(1).default(1),
  per_page: z.coerce.number().int().min(1).max(100).default(20),
});
export type TagRuleListQueryT = z.infer<typeof TagRuleListQuery>;

export const TagRuleListResponse = z.object({
  rows: z.array(TagRule),
  page: z.number().int(),
  per_page: z.number().int(),
  total: z.number().int(),
});
export type TagRuleListResponseT = z.infer<typeof TagRuleListResponse>;

export const RuleIdParam = z.object({
  tagId: Uuid,
  ruleId: Uuid,
});
export type RuleIdParamT = z.infer<typeof RuleIdParam>;
