/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/mock-login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mock login (dev only) */
    post: operations['mockLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: operations['getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List VOCs (paginated) */
    get: operations['listVocs'];
    put?: never;
    /** Create VOC */
    post: operations['createVoc'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Get VOC detail */
    get: operations['getVoc'];
    put?: never;
    post?: never;
    /** Soft-delete VOC (admin only) */
    delete: operations['deleteVoc'];
    options?: never;
    head?: never;
    /** Update VOC */
    patch: operations['updateVoc'];
    trace?: never;
  };
  '/vocs/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update VOC status */
    patch: operations['updateVocStatus'];
    trace?: never;
  };
  '/vocs/{id}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** List comments for VOC */
    get: operations['listComments'];
    put?: never;
    /** Add comment to VOC */
    post: operations['createComment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/comments/{commentId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        commentId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete comment */
    delete: operations['deleteComment'];
    options?: never;
    head?: never;
    /** Update comment */
    patch: operations['updateComment'];
    trace?: never;
  };
  '/vocs/{id}/notes': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** List internal notes (manager/admin only) */
    get: operations['listNotes'];
    put?: never;
    /** Add internal note (manager/admin only) */
    post: operations['createNote'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/notes/{noteId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        noteId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete internal note (manager/admin only) */
    delete: operations['deleteNote'];
    options?: never;
    head?: never;
    /** Update internal note (manager/admin only) */
    patch: operations['updateNote'];
    trace?: never;
  };
  '/vocs/{id}/attachments': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** List attachments for VOC */
    get: operations['listAttachments'];
    put?: never;
    /** Upload attachment */
    post: operations['uploadAttachment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/attachments/{attachmentId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        attachmentId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete attachment */
    delete: operations['deleteAttachment'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tags': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all tags */
    get: operations['listTags'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/tags': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add tag to VOC */
    post: operations['addVocTag'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/tags/{tagId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        tagId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove tag from VOC */
    delete: operations['removeVocTag'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List notifications for current user */
    get: operations['listNotifications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get unread notification count */
    get: operations['getUnreadCount'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/{id}/read': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark notification as read */
    patch: operations['markNotificationRead'];
    trace?: never;
  };
  '/dashboard/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get KPI summary (8 metrics) */
    get: operations['getDashboardSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/distribution': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get distribution by type */
    get: operations['getDashboardDistribution'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/priority-status-matrix': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get priority-status matrix */
    get: operations['getPriorityStatusMatrix'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/heatmap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get heatmap data */
    get: operations['getDashboardHeatmap'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/weekly-trend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get weekly trend */
    get: operations['getWeeklyTrend'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/tag-distribution': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get tag distribution */
    get: operations['getTagDistribution'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/system-overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get system overview stats */
    get: operations['getSystemOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/assignee-stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get assignee stats */
    get: operations['getAssigneeStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/processing-speed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get processing speed (SLA table) */
    get: operations['getProcessingSpeed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/aging': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get aging bar data */
    get: operations['getAging'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/aging-vocs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get top aging VOCs */
    get: operations['getAgingVocs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get dashboard settings */
    get: operations['getDashboardSettings'];
    /** Update dashboard settings */
    put: operations['updateDashboardSettings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/menus': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get menus for dashboard filter */
    get: operations['getDashboardMenus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/assignees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get assignees for dashboard filter */
    get: operations['getDashboardAssignees'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all users (admin) */
    get: operations['adminListUsers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update user role/status (admin) */
    patch: operations['adminUpdateUser'];
    trace?: never;
  };
  '/admin/systems': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List systems (admin) */
    get: operations['adminListSystems'];
    put?: never;
    /** Create system (admin) */
    post: operations['adminCreateSystem'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/systems/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update system (admin) */
    patch: operations['adminUpdateSystem'];
    trace?: never;
  };
  '/admin/menus': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List menus (admin) */
    get: operations['adminListMenus'];
    put?: never;
    /** Create menu (admin) */
    post: operations['adminCreateMenu'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/menus/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update menu (admin) */
    patch: operations['adminUpdateMenu'];
    trace?: never;
  };
  '/admin/voc-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List VOC types (admin) */
    get: operations['adminListVocTypes'];
    put?: never;
    /** Create VOC type (admin) */
    post: operations['adminCreateVocType'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/voc-types/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update VOC type (admin) */
    patch: operations['adminUpdateVocType'];
    trace?: never;
  };
  '/admin/tag-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tag rules (admin) */
    get: operations['adminListTagRules'];
    put?: never;
    /** Create tag rule (admin) */
    post: operations['adminCreateTagRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/tag-rules/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete tag rule (admin) */
    delete: operations['adminDeleteTagRule'];
    options?: never;
    head?: never;
    /** Update tag rule (admin) */
    patch: operations['adminUpdateTagRule'];
    trace?: never;
  };
  '/admin/masters/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh master data cache */
    post: operations['adminRefreshMasters'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/masters/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh master data for a VOC */
    post: operations['refreshVocMasters'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/payload': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit structured payload for a VOC */
    post: operations['submitVocPayload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/payload-history': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Get payload submission history for a VOC */
    get: operations['getVocPayloadHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/payload-review': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve or reject a VOC payload (Result Review) */
    post: operations['reviewVocPayload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/vocs/{id}/timeline': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Get VOC timeline events (Manager/Admin only) */
    get: operations['getVocTimeline'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/notices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List notices (admin) */
    get: operations['adminListNotices'];
    put?: never;
    /** Create notice (admin) */
    post: operations['adminCreateNotice'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/notices/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Get notice by ID (admin) */
    get: operations['adminGetNotice'];
    /** Update notice (admin) */
    put: operations['adminUpdateNotice'];
    post?: never;
    /** Delete notice (admin) */
    delete: operations['adminDeleteNotice'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/faqs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List FAQs (admin) */
    get: operations['adminListFaqs'];
    put?: never;
    /** Create FAQ (admin) */
    post: operations['adminCreateFaq'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/faqs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Get FAQ by ID (admin) */
    get: operations['adminGetFaq'];
    /** Update FAQ (admin) */
    put: operations['adminUpdateFaq'];
    post?: never;
    /** Delete FAQ (admin) */
    delete: operations['adminDeleteFaq'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    /** Download file by ID */
    get: operations['downloadFile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    OkResponse: {
      /** @enum {boolean} */
      ok: true;
    };
    ErrorResponse: {
      code: string;
      message: string;
      details?: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    UserRole: 'user' | 'manager' | 'admin';
    AuthUser: {
      /** Format: uuid */
      id: string;
      ad_username?: string | null;
      display_name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['UserRole'];
    };
    User: {
      /** Format: uuid */
      id: string;
      ad_username: string;
      display_name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['UserRole'];
      is_active: boolean;
    };
    /** @enum {string} */
    VocStatus: '접수' | '검토중' | '처리중' | '완료' | '드랍';
    /** @enum {string} */
    VocPriority: 'urgent' | 'high' | 'medium' | 'low';
    /** @enum {string} */
    VocSource: 'manual' | 'import';
    Voc: {
      /** Format: uuid */
      id: string;
      issue_code: string;
      sequence_no: number;
      title: string;
      body?: string | null;
      status: components['schemas']['VocStatus'];
      priority: components['schemas']['VocPriority'];
      /** Format: uuid */
      type_id?: string | null;
      /** Format: uuid */
      system_id?: string | null;
      /** Format: uuid */
      menu_id?: string | null;
      /** Format: uuid */
      assignee_id?: string | null;
      /** Format: uuid */
      author_id?: string;
      /** Format: uuid */
      parent_id?: string | null;
      source: components['schemas']['VocSource'];
      review_status?: string | null;
      structured_payload?: {
        [key: string]: unknown;
      } | null;
      /** @enum {string|null} */
      resolution_quality?: '근본해결' | '임시조치' | null;
      /** @enum {string|null} */
      drop_reason?: '중복' | '정책거부' | '재현불가' | '범위외' | '기타' | null;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      due_date?: string | null;
      /** Format: date-time */
      deleted_at?: string | null;
    };
    VocInput: {
      title: string;
      body?: string;
      status: components['schemas']['VocStatus'];
      priority: components['schemas']['VocPriority'];
      /** Format: uuid */
      type_id?: string;
      /** Format: uuid */
      system_id?: string;
      /** Format: uuid */
      menu_id?: string;
      /** Format: uuid */
      assignee_id?: string;
      /** Format: uuid */
      parent_id?: string;
      source?: components['schemas']['VocSource'];
    };
    VocPatch: {
      title?: string;
      body?: string;
      status?: components['schemas']['VocStatus'];
      priority?: components['schemas']['VocPriority'];
      /** Format: uuid */
      type_id?: string;
      /** Format: uuid */
      system_id?: string;
      /** Format: uuid */
      menu_id?: string;
      /** Format: uuid */
      assignee_id?: string;
      /** @enum {string} */
      review_status?: 'unverified' | 'approved' | 'rejected' | 'pending_deletion';
      /** @enum {string} */
      resolution_quality?: '근본해결' | '임시조치';
      /** @enum {string} */
      drop_reason?: '중복' | '정책거부' | '재현불가' | '범위외' | '기타';
    };
    Comment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      voc_id: string;
      /** Format: uuid */
      author_id: string;
      body: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    Note: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      voc_id: string;
      /** Format: uuid */
      author_id: string;
      body: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: date-time */
      deleted_at?: string | null;
    };
    Attachment: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      voc_id: string;
      filename: string;
      original_name: string;
      mime_type: string;
      size: number;
      url: string;
      /** Format: date-time */
      created_at: string;
    };
    Tag: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
      /** @enum {string} */
      kind: 'general' | 'menu';
      color?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    System: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
      is_archived: boolean;
    };
    SystemInput: {
      name: string;
      slug: string;
    };
    SystemPatch: {
      name?: string;
      slug?: string;
      is_archived?: boolean;
    };
    Menu: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      system_id: string;
      name: string;
      slug: string;
      is_archived: boolean;
    };
    MenuInput: {
      /** Format: uuid */
      system_id: string;
      name: string;
      slug: string;
    };
    MenuPatch: {
      name?: string;
      slug?: string;
      is_archived?: boolean;
    };
    VocType: {
      /** Format: uuid */
      id: string;
      name: string;
      slug: string;
      color?: string | null;
      sort_order: number;
      is_archived: boolean;
    };
    VocTypeInput: {
      name: string;
      slug: string;
      color?: string;
      sort_order?: number;
    };
    VocTypePatch: {
      name?: string;
      slug?: string;
      color?: string;
      sort_order?: number;
      is_archived?: boolean;
    };
    TagRule: {
      /** Format: uuid */
      id: string;
      name: string;
      pattern: string;
      /** @enum {string} */
      kind: 'general';
      /** Format: uuid */
      tag_id: string;
      is_active: boolean;
    };
    TagRuleInput: {
      name: string;
      pattern: string;
      /**
       * @default general
       * @enum {string}
       */
      kind: 'general';
      /** Format: uuid */
      tag_id: string;
      is_active?: boolean;
    };
    TagRulePatch: {
      name?: string;
      pattern?: string;
      /** @enum {string} */
      kind?: 'general';
      /** Format: uuid */
      tag_id?: string;
      is_active?: boolean;
    };
    Notification: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      user_id: string;
      /** @enum {string} */
      type: 'status_change' | 'comment' | 'mention' | 'assignment' | 'urgent';
      /** Format: uuid */
      voc_id?: string | null;
      message: string;
      is_read: boolean;
      /** Format: date-time */
      created_at: string;
    };
    PaginatedVocs: {
      items: components['schemas']['Voc'][];
      total: number;
      page: number;
      limit: number;
      totalPages: number;
    };
    DashboardSummary: {
      total: number;
      open: number;
      in_progress: number;
      completed: number;
      dropped: number;
      urgent: number;
      overdue: number;
      avg_resolution_days: number;
    };
    DashboardSettings: {
      [key: string]: unknown;
    };
    DistributionItem: {
      label: string;
      count: number;
      percentage?: number;
    };
    WeeklyTrendItem: {
      week: string;
      count: number;
    };
    TagStatItem: {
      /** Format: uuid */
      tag_id: string;
      name: string;
      count: number;
    };
    SystemStatItem: {
      /** Format: uuid */
      system_id: string;
      name: string;
      count: number;
    };
    MasterRefreshResult: {
      swapped: boolean;
      /** Format: date-time */
      loaded_at: string;
    };
    VocPayloadHistory: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      voc_id: string;
      payload: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      submitted_by: string;
      /** Format: date-time */
      submitted_at: string;
      final_state?: string | null;
      is_current: boolean;
    };
    Notice: {
      /** Format: uuid */
      id: string;
      title: string;
      body: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    NoticeInput: {
      title: string;
      body: string;
    };
    Faq: {
      /** Format: uuid */
      id: string;
      question: string;
      answer: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    FaqInput: {
      question: string;
      answer: string;
    };
  };
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Forbidden */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description Not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    id: string;
    page: number;
    limit: number;
    dashboardSystemId: string;
    dashboardMenuId: string;
    dashboardAssigneeId: string;
    dashboardStartDate: string;
    dashboardEndDate: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
            /** @enum {string} */
            db: 'ok';
            uptime: number;
          };
        };
      };
    };
  };
  mockLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          role: 'admin' | 'manager' | 'user';
        };
      };
    };
    responses: {
      /** @description Logged in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: components['schemas']['AuthUser'];
          };
        };
      };
      400: components['responses']['BadRequest'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthUser'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  listVocs: {
    parameters: {
      query?: {
        page?: components['parameters']['page'];
        limit?: components['parameters']['limit'];
        status?: components['schemas']['VocStatus'];
        priority?: components['schemas']['VocPriority'];
        systemId?: string;
        menuId?: string;
        type?: string;
        assigneeId?: string;
        q?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        includeDeleted?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated VOC list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedVocs'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  createVoc: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VocInput'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Voc'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  getVoc: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description VOC */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Voc'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  deleteVoc: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateVoc: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VocPatch'];
      };
    };
    responses: {
      /** @description Updated VOC */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Voc'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  updateVocStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          status: components['schemas']['VocStatus'];
        };
      };
    };
    responses: {
      /** @description Updated VOC */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Voc'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  listComments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Comment'][];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          body: string;
        };
      };
    };
    responses: {
      /** @description Created comment */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Comment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  updateComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        commentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          body: string;
        };
      };
    };
    responses: {
      /** @description Updated comment */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Comment'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  listNotes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'][];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  createNote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          body: string;
        };
      };
    };
    responses: {
      /** @description Created note */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  deleteNote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        noteId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateNote: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        noteId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          body: string;
        };
      };
    };
    responses: {
      /** @description Updated note */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Note'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  listAttachments: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attachments */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Attachment'][];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  uploadAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Created attachment */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Attachment'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  deleteAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        attachmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  listTags: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tags */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Tag'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  addVocTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uuid */
          tagId: string;
        };
      };
    };
    responses: {
      /** @description Tag added */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  removeVocTag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
        tagId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tag removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  listNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notification'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getUnreadCount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Count */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count: number;
          };
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  markNotificationRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Marked read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  getDashboardSummary: {
    parameters: {
      query?: {
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description KPI summary */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardSummary'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getDashboardDistribution: {
    parameters: {
      query: {
        type: 'status' | 'priority' | 'voc_type' | 'tag';
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Distribution array */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DistributionItem'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getPriorityStatusMatrix: {
    parameters: {
      query?: {
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Matrix */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getDashboardHeatmap: {
    parameters: {
      query?: {
        xAxis?: 'status' | 'priority' | 'tag';
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Heatmap */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getWeeklyTrend: {
    parameters: {
      query?: {
        weeks?: number;
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Trend array */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WeeklyTrendItem'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getTagDistribution: {
    parameters: {
      query?: {
        limit?: number;
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tag stats */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagStatItem'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getSystemOverview: {
    parameters: {
      query?: {
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description System stats */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SystemStatItem'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getAssigneeStats: {
    parameters: {
      query?: {
        xAxis?: 'status' | 'priority' | 'tag';
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assignee stats */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getProcessingSpeed: {
    parameters: {
      query?: {
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SLA table */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getAging: {
    parameters: {
      query?: {
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Aging bar data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getAgingVocs: {
    parameters: {
      query?: {
        limit?: number;
        systemId?: components['parameters']['dashboardSystemId'];
        menuId?: components['parameters']['dashboardMenuId'];
        assigneeId?: components['parameters']['dashboardAssigneeId'];
        startDate?: components['parameters']['dashboardStartDate'];
        endDate?: components['parameters']['dashboardEndDate'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Top aging VOCs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Voc'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getDashboardSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardSettings'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  updateDashboardSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DashboardSettings'];
      };
    };
    responses: {
      /** @description Updated settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardSettings'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
    };
  };
  getDashboardMenus: {
    parameters: {
      query?: {
        systemId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Menus */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Menu'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  getDashboardAssignees: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'][];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  adminListUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminUpdateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          role?: components['schemas']['UserRole'];
          is_active?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListSystems: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Systems */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['System'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateSystem: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SystemInput'];
      };
    };
    responses: {
      /** @description Created system */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['System'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminUpdateSystem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SystemPatch'];
      };
    };
    responses: {
      /** @description Updated system */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['System'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListMenus: {
    parameters: {
      query?: {
        systemId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Menus */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Menu'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateMenu: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MenuInput'];
      };
    };
    responses: {
      /** @description Created menu */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Menu'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminUpdateMenu: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MenuPatch'];
      };
    };
    responses: {
      /** @description Updated menu */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Menu'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListVocTypes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description VOC types */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VocType'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateVocType: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VocTypeInput'];
      };
    };
    responses: {
      /** @description Created VOC type */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VocType'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminUpdateVocType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VocTypePatch'];
      };
    };
    responses: {
      /** @description Updated VOC type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VocType'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListTagRules: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tag rules */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagRule'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateTagRule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TagRuleInput'];
      };
    };
    responses: {
      /** @description Created tag rule */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagRule'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminDeleteTagRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminUpdateTagRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TagRulePatch'];
      };
    };
    responses: {
      /** @description Updated tag rule */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TagRule'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminRefreshMasters: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MasterRefreshResult'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  refreshVocMasters: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Refresh result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MasterRefreshResult'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  submitVocPayload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          equipment: string;
          maker: string;
          model: string;
          process: string;
          symptom: string;
          root_cause: string;
          resolution: string;
          unverified_fields?: string[];
        };
      };
    };
    responses: {
      /** @description Submitted payload history entry */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VocPayloadHistory'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getVocPayloadHistory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payload history list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VocPayloadHistory'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  reviewVocPayload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          decision: 'approved' | 'rejected';
          comment?: string | null;
        };
      };
    };
    responses: {
      /** @description Review recorded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getVocTimeline: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Timeline event list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          }[];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListNotices: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notice list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notice'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateNotice: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NoticeInput'];
      };
    };
    responses: {
      /** @description Created notice */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notice'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminGetNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notice */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notice'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminUpdateNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NoticeInput'];
      };
    };
    responses: {
      /** @description Updated notice */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Notice'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminDeleteNotice: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminListFaqs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description FAQ list */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Faq'][];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminCreateFaq: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FaqInput'];
      };
    };
    responses: {
      /** @description Created FAQ */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Faq'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  adminGetFaq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description FAQ */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Faq'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminUpdateFaq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FaqInput'];
      };
    };
    responses: {
      /** @description Updated FAQ */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Faq'];
        };
      };
      400: components['responses']['BadRequest'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  adminDeleteFaq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OkResponse'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  downloadFile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File binary content */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/octet-stream': string;
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
}
